//! Step definition trait for the `#[step]` macro.
//!
//! The `StepDefinition` trait is implemented by structs generated by the `#[step]` macro.
//! It provides metadata about the transition step that can be introspected at runtime.

/// Trait for step definitions generated by the `#[step]` macro.
///
/// This trait provides metadata about a transition step, including its ID, name,
/// input/output port definitions, and the Rhai script logic.
///
/// # Example
///
/// ```ignore
/// use aithericon_sdk::{step, StepDefinition};
///
/// #[step("allocate", "Allocate Task")]
/// fn allocate(task: Task, worker: Worker) -> Assignment {
///     Assignment { task_id: task.id, worker_id: worker.id }
/// }
///
/// // Access metadata:
/// println!("Step ID: {}", AllocateStep::id());
/// println!("Step name: {}", AllocateStep::name());
/// println!("Inputs: {:?}", AllocateStep::inputs());
/// println!("Output: {:?}", AllocateStep::output());
/// println!("Script: {}", AllocateStep::script());
/// ```
pub trait StepDefinition {
    /// The transition ID (scenario-level identifier).
    ///
    /// This is used as the key when wiring the transition in the context.
    fn id() -> &'static str;

    /// Human-readable transition name.
    ///
    /// Displayed in the UI and logs.
    fn name() -> &'static str;

    /// Input ports as (port_name, type_name) pairs.
    ///
    /// Each entry corresponds to a function parameter in the original step function.
    fn inputs() -> &'static [(&'static str, &'static str)];

    /// Output port as (port_name, type_name).
    ///
    /// Derived from the function's return type.
    fn output() -> (&'static str, &'static str);

    /// The Rhai script logic.
    ///
    /// Generated from the function body by converting Rust syntax to Rhai.
    fn script() -> &'static str;
}
