use std::path::Path;

use aithericon_executor_domain::ExecutorError;

/// Write the Python runner template that wraps user code.
///
/// The runner exposes upstream workflow data as plain Python globals — one
/// per `<slug>.json` staged input (e.g. an upstream `review` AutomatedStep
/// becomes a `review` namespace; `review.invoice_amount` is a normal
/// attribute lookup). The compiler synthesizes a read-arc + stages the
/// producer's parked envelope whenever a `<slug>.<attr>` access is
/// detected in user source, so authors never write `token[...]` or call
/// the SDK to read borrowed data.
///
/// Still injected for compatibility / SDK helpers:
/// 1. `token` / `input` — the slim control token (Start fields + metadata),
///    loaded from `input.json`.
/// 2. `inputs` — raw staged-file map (escape hatch for binary or named
///    files).
/// 3. `set_output(name, value)` — file-based output that writes JSON to
///    `AITHERICON_OUTPUTS_DIR`.
/// 4. If the `aithericon` SDK is installed, upgrades `set_output` + adds
///    IPC-backed artifacts, progress, logging, and metrics (`token` stays
///    the dict view; the SDK path doesn't replace it any more).
pub async fn write_runner(
    runner_path: &Path,
    user_code_path: &Path,
    declared_outputs: &[(String, bool, Option<String>)],
) -> Result<(), ExecutorError> {
    let user_code_escaped = user_code_path
        .to_string_lossy()
        .replace('\\', "\\\\")
        .replace('\'', "\\'");

    // Bake declared output names + kinds into the runner template so the
    // post-exec sweep can promote matching Python globals to `<name>.json`
    // files AND strict-validate each emitted JSON value against the declared
    // FieldKind (gated by PETRI_VALIDATE_SCHEMAS, default on — see
    // engine/core-engine/src/config.rs). The compile-time
    // `OutputFieldShadowsReserved` / `OutputFieldShadowsInput` guards in
    // service/src/compiler/compile.rs reject collisions, so any name
    // reaching this list is safe to write.
    let declared_list = declared_outputs
        .iter()
        .map(|(name, _, _)| format!("{:?}", name))
        .collect::<Vec<_>>()
        .join(", ");
    let required_list = declared_outputs
        .iter()
        .filter(|(_, required, _)| *required)
        .map(|(name, _, _)| format!("{:?}", name))
        .collect::<Vec<_>>()
        .join(", ");
    // Kinds dict literal: `"vendor": "text", "amount": "number", ...`.
    // Entries with no declared kind (None) are omitted so the runner skips
    // them in the validation pass — back-compat for jobs whose service-side
    // compiler doesn't yet emit kinds.
    let kinds_dict = declared_outputs
        .iter()
        .filter_map(|(name, _, kind)| kind.as_ref().map(|k| format!("{:?}: {:?}", name, k)))
        .collect::<Vec<_>>()
        .join(", ");

    let template = format!(
        r#"#!/usr/bin/env python3
# Generated by PythonBackend — do not edit
import sys
import os
import json

# Setup paths
_run_dir = os.environ.get("AITHERICON_RUN_DIR", os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _run_dir)
_inputs_dir = os.environ.get("AITHERICON_INPUTS_DIR")
if _inputs_dir:
    sys.path.insert(0, _inputs_dir)
os.chdir(_run_dir)

# --- Attribute-accessible dict ---
class _AccessibleDict(dict):
    """A dict that also supports attribute access for its keys, so a
    workflow producer envelope staged as `<slug>.json` can be read as
    `<slug>.<field>` from user code without any wrapper. Nested dicts
    and list elements are wrapped recursively.

    Lookup precedence: non-dunder keys in the dict win over inherited
    dict methods (so `batch.items[0]` reads a user `items` field, not
    `dict.items` the method). If no key matches, normal attribute lookup
    proceeds — so `review.keys()` still works as the dict method when
    `review` has no `keys` field. To call a dict method on a wrapper
    that DOES have a shadowing key, use `dict.<method>(wrapper)`.

    Missing attribute access (no key + no inherited method) raises
    AttributeError, so `hasattr` / `getattr(obj, key, default)` keep
    their documented semantics."""
    def __getattribute__(self, key):
        if not key.startswith('_'):
            try:
                return dict.__getitem__(self, key)
            except KeyError:
                pass
        return super().__getattribute__(key)

    def __setattr__(self, key, value):
        self[key] = value


def _accessible(value):
    if isinstance(value, dict):
        return _AccessibleDict({{k: _accessible(v) for k, v in value.items()}})
    if isinstance(value, list):
        return [_accessible(v) for v in value]
    return value


# --- Load inputs ---
def _load_inputs():
    inputs_dir = os.environ.get("AITHERICON_INPUTS_DIR")
    if not inputs_dir or not os.path.isdir(inputs_dir):
        return {{}}
    result = {{}}
    for entry in os.listdir(inputs_dir):
        path = os.path.join(inputs_dir, entry)
        if not os.path.isfile(path):
            continue
        try:
            with open(path, encoding="utf-8") as f:
                content = f.read()
        except (UnicodeDecodeError, OSError):
            # Binary reference file (e.g. *.npy). Leave it on disk under
            # AITHERICON_INPUTS_DIR; user code can open it by path.
            continue
        try:
            result[entry] = json.loads(content)
        except (json.JSONDecodeError, ValueError):
            result[entry] = content
    return result

inputs = _load_inputs()

# Slim control token (Start fields + `_*` metadata + `task_id`/`status`),
# loaded from the staged `input.json`. Available as both `token` (legacy
# name) and `input` (the natural reading: "this is the inbound token").
# Wrapped so `token.<field>` works the same way as upstream slug
# namespaces, no `token["field"]` ceremony needed.
_input_raw = inputs.get("input.json", {{}}) if isinstance(inputs, dict) else {{}}
token = _accessible(_input_raw) if isinstance(_input_raw, dict) else _input_raw
input = token  # noqa: A001  the natural Python reading; shadowing the
               # builtin is acceptable inside a workflow step where the
               # input is the central named value.

# Expose each `<slug>.json` staged input as a top-level Python global so
# `<slug>.<field>` is a plain attribute lookup. The compiler stages one
# producer envelope per upstream `<slug>.<attr>` reference detected in
# this step's source (see service/src/compiler/python_refs.rs). Names that
# would clash with the runner's own SDK helpers are skipped — the picker
# warns at edit time but the runtime stays correct.
_RESERVED_GLOBALS = {{
    "token", "input", "inputs", "set_output", "load_inputs",
    "log_info", "log_warn", "log_error", "log_debug", "log_metric",
    "log_artifact", "update_progress", "define_phases", "update_phase",
    "aithericon", "sys", "os", "json",
}}
for _name, _value in (inputs.items() if isinstance(inputs, dict) else []):
    if not isinstance(_name, str) or not _name.endswith(".json") or _name == "input.json":
        continue
    _slug = _name[:-5]
    if not _slug or not _slug.isidentifier() or _slug in _RESERVED_GLOBALS:
        continue
    globals()[_slug] = _accessible(_value)


# --- Output helper (file-based fallback) ---
def set_output(name, value):
    """Set a named output value. Writes JSON to the outputs directory."""
    outputs_dir = os.environ.get("AITHERICON_OUTPUTS_DIR")
    if outputs_dir:
        os.makedirs(outputs_dir, exist_ok=True)
        with open(os.path.join(outputs_dir, name + ".json"), "w") as f:
            json.dump(value, f)


# --- Try to upgrade to SDK (IPC-backed) ---
try:
    import aithericon
    _ipc_sock = os.environ.get("AITHERICON_IPC_SOCKET", "")
    import sys as _sys
    print(f"[runner] SDK imported, socket={{_ipc_sock}}, python={{_sys.executable}}", file=_sys.stderr)
    aithericon.init()
    print(f"[runner] SDK init ok, connected={{aithericon._client.is_connected()}}", file=_sys.stderr)
    # The dict view of `token` is the authoritative one for the new direct
    # slug-access model — don't swap it for an IPC handle here, or
    # `token.field` would stop working. SDK still upgrades the
    # side-effectful helpers.
    set_output = aithericon.set_output
    log_artifact = aithericon.log_artifact
    update_progress = aithericon.update_progress
    define_phases = aithericon.define_phases
    update_phase = aithericon.update_phase
    log_info = aithericon.log_info
    log_warn = aithericon.log_warn
    log_error = aithericon.log_error
    log_debug = aithericon.log_debug
    log_metric = aithericon.log_metric
except ImportError as _e:
    import sys as _sys
    print(f"[runner] SDK import failed: {{_e}}", file=_sys.stderr)
    pass  # SDK not installed — file-based set_output still works

# --- Execute user code ---
exec(open('{user_code_escaped}', encoding='utf-8').read())

# --- Implicit output sweep ---
# Declared output.fields[].name from the workflow editor — the compiler
# bakes this list in per execution. After user code finishes, walk the
# list and promote each name found in globals() to `<name>.json`. Skip
# names whose file already exists, so an explicit `set_output(name, v)`
# inside user code wins (explicit-beats-implicit by recency: set_output
# already wrote the file during exec). Required names with no file at
# this point are a hard error — the executor-worker would fail to
# project the missing output downstream, so fail fast here with a clear
# message instead of surfacing as a confusing NoSuchKey later.
_DECLARED_OUTPUTS = [{declared_list}]
_REQUIRED_OUTPUTS = [{required_list}]
_outputs_dir = os.environ.get("AITHERICON_OUTPUTS_DIR")
if _outputs_dir and _DECLARED_OUTPUTS:
    os.makedirs(_outputs_dir, exist_ok=True)
    for _decl_name in _DECLARED_OUTPUTS:
        _decl_path = os.path.join(_outputs_dir, _decl_name + ".json")
        if os.path.exists(_decl_path):
            continue
        if _decl_name not in globals():
            continue
        try:
            with open(_decl_path, "w") as _decl_f:
                json.dump(globals()[_decl_name], _decl_f)
        except (TypeError, ValueError) as _decl_e:
            print(
                f"[runner] implicit output {{_decl_name!r}} not JSON-serializable: {{_decl_e}}",
                file=sys.stderr,
            )
if _outputs_dir and _REQUIRED_OUTPUTS:
    _missing = [
        _req_name
        for _req_name in _REQUIRED_OUTPUTS
        if not os.path.exists(os.path.join(_outputs_dir, _req_name + ".json"))
    ]
    if _missing:
        print(
            f"[runner] missing required output(s): {{_missing!r}}",
            file=sys.stderr,
        )
        try:
            aithericon.shutdown()
        except NameError:
            pass
        sys.exit(2)

# --- Strict kind validation (PETRI_VALIDATE_SCHEMAS gate) ---
# Validate each emitted output value against its declared FieldKind, hard-
# rejecting on mismatch so authors see the precise source of the problem
# at the runner instead of a generic JSON Schema failure at the petri
# layer downstream. Covers BOTH paths uniformly — files written by the
# implicit sweep above AND files written by explicit set_output earlier.
# Default-on; PETRI_VALIDATE_SCHEMAS=false/0 disables, matching the
# engine's posture (engine/core-engine/src/config.rs:243). Names with no
# declared kind (back-compat with pre-typed jobs) skip validation.
_DECLARED_KINDS = {{{kinds_dict}}}
_validate_schemas = (
    os.environ.get("PETRI_VALIDATE_SCHEMAS", "true").lower() not in ("false", "0")
)

def _kind_accepts(_kind, _value):
    # Mirror of FieldKind::accepts in service/src/models/template.rs.
    # `bool` is checked FIRST because in Python `True` / `False` are int
    # subclasses, so `isinstance(True, (int, float))` returns True — the
    # naive Number check would silently accept a bool where a number is
    # required.
    if _kind == "json":
        return True
    if _kind == "bool":
        return isinstance(_value, bool)
    if _kind == "number":
        return isinstance(_value, (int, float)) and not isinstance(_value, bool)
    if _kind in ("text", "textarea", "select", "signature", "timestamp"):
        return isinstance(_value, str)
    if _kind == "file":
        return isinstance(_value, (str, dict))
    # Unknown kind: forward-compat with future FieldKind additions whose
    # rollout reaches the service before the executor. Skip rather than
    # falsely reject.
    return True

if _validate_schemas and _outputs_dir and _DECLARED_KINDS:
    _kind_errors = []
    for _vname, _vkind in _DECLARED_KINDS.items():
        _vpath = os.path.join(_outputs_dir, _vname + ".json")
        if not os.path.exists(_vpath):
            # Either an optional output not emitted, or a required one
            # already caught above. Either way, no value to validate.
            continue
        try:
            with open(_vpath) as _vf:
                _vval = json.load(_vf)
        except (OSError, json.JSONDecodeError) as _ve:
            _kind_errors.append((_vname, _vkind, f"unreadable: {{_ve}}"))
            continue
        if not _kind_accepts(_vkind, _vval):
            _kind_errors.append(
                (_vname, _vkind, type(_vval).__name__)
            )
    if _kind_errors:
        for (_en, _ek, _et) in _kind_errors:
            print(
                f"[runner] declared output {{_en!r}} kind={{_ek!r}} got {{_et}} — value rejected",
                file=sys.stderr,
            )
        try:
            aithericon.shutdown()
        except NameError:
            pass
        sys.exit(3)

# --- Cleanup ---
try:
    aithericon.shutdown()
except NameError:
    pass
"#
    );

    tokio::fs::write(runner_path, template)
        .await
        .map_err(|e| ExecutorError::StagingFailed(format!("failed to write runner template: {e}")))
}

#[cfg(test)]
mod tests {
    //! Runner-template behaviour tests.
    //!
    //! These prove the contract the compiler-side relies on: every
    //! `<slug>.json` staged in `AITHERICON_INPUTS_DIR` becomes a Python
    //! global the user's `exec`-loaded code can read by attribute (and
    //! by item) access. The compiler-side `automated_step_borrow_plan`
    //! decides *which* slugs get staged; this layer proves they reach
    //! user code intact.
    //!
    //! Strategy: write the runner to a temp dir, populate inputs/,
    //! invoke `python3` on it with a small user script, capture stdout
    //! and assert. No NATS, no IPC sidecar, no SDK — these tests
    //! deliberately drive the non-SDK path. The SDK-upgraded path is
    //! exercised by live dev (see the `executor-separate-binary`
    //! memory).
    //!
    //! Skipped at runtime when either:
    //!   - `python3` is not on PATH (CI Linux containers without it)
    //!   - the system `python3` can `import aithericon` (the runner
    //!     would then call `aithericon.init()` and try to connect to
    //!     a non-existent IPC socket, which is out of scope here)
    use super::*;
    use std::process::Command;
    use tempfile::TempDir;

    /// `true` when `python3` is missing — caller skips the test.
    fn skip_no_python3() -> bool {
        Command::new("python3")
            .arg("--version")
            .output()
            .map(|o| !o.status.success())
            .unwrap_or(true)
    }

    /// `true` when system python3 has `aithericon` importable — the
    /// runner would init the SDK and try to connect to a missing IPC
    /// socket. Skip in that case; the SDK path is verified by live
    /// dev, not by these unit tests.
    fn skip_with_sdk() -> bool {
        Command::new("python3")
            .args(["-c", "import aithericon"])
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    /// Stage `<inputs>/main.py` plus any extra inputs, write the runner
    /// template, invoke `python3 <runner>` with the env vars the
    /// executor sets, return `(stdout, stderr, exit_code)`.
    async fn run_runner(
        user_script: &str,
        inputs: &[(&str, &str)],
    ) -> (String, String, i32) {
        let temp = TempDir::new().expect("temp dir");
        let run_dir = temp.path();
        let inputs_dir = run_dir.join("inputs");
        std::fs::create_dir_all(&inputs_dir).unwrap();

        let user_path = inputs_dir.join("main.py");
        std::fs::write(&user_path, user_script).unwrap();

        for (name, content) in inputs {
            std::fs::write(inputs_dir.join(name), content).unwrap();
        }

        let runner_path = run_dir.join("__runner__.py");
        write_runner(&runner_path, &user_path, &[])
            .await
            .expect("write_runner");

        let outputs_dir = run_dir.join("outputs");
        std::fs::create_dir_all(&outputs_dir).unwrap();

        let output = Command::new("python3")
            .arg(&runner_path)
            .env("AITHERICON_RUN_DIR", run_dir)
            .env("AITHERICON_INPUTS_DIR", &inputs_dir)
            .env("AITHERICON_OUTPUTS_DIR", &outputs_dir)
            .env("PYTHONDONTWRITEBYTECODE", "1")
            .output()
            .expect("python3 invocation");

        let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        let code = output.status.code().unwrap_or(-1);
        drop(temp);
        (stdout, stderr, code)
    }

    /// Skip the body when the environment can't run runner tests.
    macro_rules! skip_if_env_unsupported {
        () => {
            if skip_no_python3() {
                eprintln!("skipped: python3 not on PATH");
                return;
            }
            if skip_with_sdk() {
                eprintln!(
                    "skipped: aithericon importable in system python3; \
                     runner would try to connect to an IPC socket"
                );
                return;
            }
        };
    }

    #[tokio::test]
    async fn slug_global_resolves_via_attribute_access() {
        skip_if_env_unsupported!();
        let (stdout, stderr, code) = run_runner(
            "print(review.invoice_amount)",
            &[
                ("input.json", "{}"),
                (
                    "review.json",
                    r#"{"invoice_amount": 1234.5, "vendor_name": "ACME"}"#,
                ),
            ],
        )
        .await;
        assert_eq!(code, 0, "stdout: {stdout}\nstderr: {stderr}");
        assert_eq!(stdout.trim(), "1234.5");
    }

    #[tokio::test]
    async fn slug_global_supports_item_access_too() {
        skip_if_env_unsupported!();
        let (stdout, stderr, code) = run_runner(
            r#"print(review["vendor_name"])"#,
            &[("review.json", r#"{"vendor_name": "ACME"}"#)],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "ACME");
    }

    #[tokio::test]
    async fn nested_dict_recursively_accessible() {
        skip_if_env_unsupported!();
        let (stdout, stderr, code) = run_runner(
            "print(extract.result.amount, extract.result.vendor)",
            &[(
                "extract.json",
                r#"{"result": {"amount": 100, "vendor": "X"}}"#,
            )],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "100 X");
    }

    #[tokio::test]
    async fn list_elements_wrapped_recursively() {
        skip_if_env_unsupported!();
        let (stdout, stderr, code) = run_runner(
            "print(batch.items[0].id, batch.items[1].id)",
            &[("batch.json", r#"{"items": [{"id": "a"}, {"id": "b"}]}"#)],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "a b");
    }

    #[tokio::test]
    async fn missing_attribute_raises_attribute_error_not_keyerror() {
        skip_if_env_unsupported!();
        // hasattr / getattr-with-default both rely on AttributeError
        // semantics — if we raised KeyError, neither would work as
        // documented.
        let (stdout, stderr, code) = run_runner(
            "print('has' if hasattr(review, 'present') else 'no')\n\
             print(getattr(review, 'missing', 'fallback'))",
            &[("review.json", r#"{"present": 1}"#)],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "has\nfallback");
    }

    #[tokio::test]
    async fn reserved_global_names_are_not_shadowed() {
        skip_if_env_unsupported!();
        // A staged file named "set_output.json" must NOT overwrite the
        // runner-injected helper. The reserved-globals guard in the
        // template skips slug names that would clash.
        let (stdout, stderr, code) = run_runner(
            "print(callable(set_output))",
            &[
                ("input.json", "{}"),
                ("set_output.json", r#"{"shadow": "boom"}"#),
            ],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "True");
    }

    #[tokio::test]
    async fn input_json_loaded_as_both_token_and_input() {
        skip_if_env_unsupported!();
        // The slim control token (Start fields + identity/metadata) is
        // available under BOTH names so legacy `token` code keeps
        // working AND `input.<field>` reads naturally.
        let (stdout, stderr, code) = run_runner(
            "print(token.invoice_id, input.invoice_id)",
            &[("input.json", r#"{"invoice_id": "INV-42"}"#)],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "INV-42 INV-42");
    }

    #[tokio::test]
    async fn non_identifier_filename_silently_skipped() {
        skip_if_env_unsupported!();
        // A filename like "weird-name.json" cannot be a Python global
        // (the `-` breaks the identifier rule). The runner must skip
        // it without crashing — user code just won't see a global by
        // that name, and `inputs["weird-name.json"]` stays available
        // as the escape hatch.
        let (stdout, stderr, code) = run_runner(
            r#"print("ok", "weird-name.json" in inputs)"#,
            &[
                ("input.json", "{}"),
                ("weird-name.json", r#"{"x": 1}"#),
            ],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "ok True");
    }

    #[tokio::test]
    async fn non_dict_top_level_value_passes_through_unwrapped() {
        skip_if_env_unsupported!();
        // A `<slug>.json` whose top-level is a scalar / list still
        // binds the global — just without the AccessibleDict wrapper
        // (wrapping a non-dict would be wrong; the value IS the value).
        let (stdout, stderr, code) = run_runner(
            "print(scalar, type(scalar).__name__)",
            &[("scalar.json", "42")],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "42 int");
    }

    #[tokio::test]
    async fn missing_input_json_yields_empty_token() {
        skip_if_env_unsupported!();
        // No input.json staged — `token` and `input` exist as empty
        // dicts so `token.get('x', default)` still works and
        // `'x' in token` returns False instead of NameError.
        let (stdout, stderr, code) = run_runner(
            r#"print(token.get("x", "default"), "x" in token)"#,
            &[],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "default False");
    }

    #[tokio::test]
    async fn multiple_slug_globals_coexist() {
        skip_if_env_unsupported!();
        // The compile-side borrow planner emits one stage entry per
        // (consumer, producer); the runner must promote *all* of them
        // to globals independently.
        let (stdout, stderr, code) = run_runner(
            "print(review.invoice_amount, scan.text, extract.amount)",
            &[
                ("input.json", "{}"),
                ("review.json", r#"{"invoice_amount": 100}"#),
                ("scan.json", r#"{"text": "hello"}"#),
                ("extract.json", r#"{"amount": 42}"#),
            ],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "100 hello 42");
    }

    #[tokio::test]
    async fn dict_methods_still_work_when_no_shadowing_key() {
        skip_if_env_unsupported!();
        // The AccessibleDict's getattribute prefers keys over inherited
        // dict methods. When NO shadowing key exists, the normal dict
        // method must still be reachable so `for k in review.keys()`,
        // `review.get('x', default)`, etc. behave like a normal dict.
        let (stdout, stderr, code) = run_runner(
            "ks = list(review.keys())\n\
             ks.sort()\n\
             print(','.join(ks))\n\
             print(review.get('missing_field', 'fallback'))",
            &[("review.json", r#"{"alpha": 1, "beta": 2}"#)],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "alpha,beta\nfallback");
    }

    #[tokio::test]
    async fn key_shadowing_dict_method_returns_value_not_method() {
        skip_if_env_unsupported!();
        // When a user field name shadows a dict method (`items`, `keys`,
        // `values`, ...), attribute access must return the VALUE — the
        // alternative would silently mask user data behind the inherited
        // method, the precise footgun the AccessibleDict guards against.
        // The dict method is still reachable via `dict.<method>(d)`.
        let (stdout, stderr, code) = run_runner(
            "print(batch.items)\n\
             print(sorted(dict.items(batch)))",
            &[("batch.json", r#"{"items": [1, 2, 3]}"#)],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "[1, 2, 3]\n[('items', [1, 2, 3])]");
    }

    #[tokio::test]
    async fn user_script_not_promoted_as_global() {
        skip_if_env_unsupported!();
        // The production staging layout puts `main.py` alongside the
        // staged `<slug>.json` envelopes in AITHERICON_INPUTS_DIR. The
        // slug-globals loop must ONLY promote `.json` files — the user's
        // own `main.py` source must not appear as a global named `main`
        // or shadow anything.
        let (stdout, stderr, code) = run_runner(
            "print('main' in globals(), type(inputs.get('main.py')).__name__)",
            &[("input.json", "{}")],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        // `main` not promoted; runner *does* load main.py text into the
        // inputs dict (escape hatch — user can inspect their own source).
        assert_eq!(stdout.trim(), "False str");
    }

    #[tokio::test]
    async fn invalid_json_slug_falls_back_to_raw_string_global() {
        skip_if_env_unsupported!();
        // `<slug>.json` whose content isn't valid JSON falls back to the
        // raw string (see `_load_inputs`). The slug-globals loop still
        // promotes it — `_accessible(str)` returns the string unchanged,
        // so `notes` is just the file contents. Locks down the fallback
        // semantics so a corrupt envelope doesn't crash the runner.
        let (stdout, stderr, code) = run_runner(
            "print(type(notes).__name__, len(notes) > 0)",
            &[("notes.json", "this is not json")],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "str True");
    }

    #[tokio::test]
    async fn empty_inputs_dir_does_not_crash() {
        skip_if_env_unsupported!();
        // The no-borrow case: compile-time `automated_step_borrow_plan`
        // detected zero `<slug>.<attr>` reads, so the executor stages no
        // envelopes — just the user script. Runner must boot with `token`
        // / `input` as empty dicts and run user code without error.
        let (stdout, stderr, code) = run_runner(
            "print(type(token).__name__, len(token), 'review' in globals())",
            &[],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        // _AccessibleDict is a dict subclass; len(empty) == 0; no slug global.
        assert_eq!(stdout.trim(), "_AccessibleDict 0 False");
    }

    #[tokio::test]
    async fn binary_file_in_inputs_skipped_gracefully() {
        skip_if_env_unsupported!();
        // The runner's _load_inputs catches UnicodeDecodeError on binary
        // files (e.g. `.npy`) and leaves them on disk — user code opens
        // by path. This test stages a real binary blob; the runner must
        // not crash and the named global must not exist (it's not .json,
        // and even if it were, the bytes wouldn't decode).
        use std::io::Write;
        let temp = TempDir::new().unwrap();
        let run_dir = temp.path();
        let inputs_dir = run_dir.join("inputs");
        std::fs::create_dir_all(&inputs_dir).unwrap();

        let mut bin = std::fs::File::create(inputs_dir.join("blob.npy")).unwrap();
        bin.write_all(&[0x93, 0x4E, 0x55, 0x4D, 0x50, 0x59, 0x01, 0x00, 0xFF, 0xFE])
            .unwrap();
        std::fs::write(inputs_dir.join("input.json"), "{}").unwrap();

        let user_path = inputs_dir.join("main.py");
        std::fs::write(
            &user_path,
            "import os\n\
             print(os.path.isfile(os.path.join(os.environ['AITHERICON_INPUTS_DIR'], 'blob.npy')))\n\
             print('blob' in globals())",
        )
        .unwrap();
        let runner_path = run_dir.join("__runner__.py");
        write_runner(&runner_path, &user_path, &[]).await.unwrap();

        let outputs_dir = run_dir.join("outputs");
        std::fs::create_dir_all(&outputs_dir).unwrap();

        let output = Command::new("python3")
            .arg(&runner_path)
            .env("AITHERICON_RUN_DIR", run_dir)
            .env("AITHERICON_INPUTS_DIR", &inputs_dir)
            .env("AITHERICON_OUTPUTS_DIR", &outputs_dir)
            .env("PYTHONDONTWRITEBYTECODE", "1")
            .output()
            .unwrap();
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(output.status.success(), "stderr: {stderr}");
        // Binary file: kept on disk, NOT promoted.
        assert_eq!(stdout.trim(), "True\nFalse");
    }

    #[tokio::test]
    async fn slug_global_with_top_level_list_passes_through() {
        skip_if_env_unsupported!();
        // Top-level list-shaped envelope: `_accessible` wraps inner dicts
        // but leaves the outer list as a list. The compiler emits these
        // for upstream nodes whose output is naturally a sequence.
        let (stdout, stderr, code) = run_runner(
            "print(len(records), records[0].id, records[1].id)",
            &[("records.json", r#"[{"id": "a"}, {"id": "b"}]"#)],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "2 a b");
    }

    #[tokio::test]
    async fn empty_slug_envelope_promotes_as_empty_namespace() {
        skip_if_env_unsupported!();
        // `<slug>.json` containing `{}` (producer emitted no fields)
        // still promotes — user code may do `getattr(slug, 'x', default)`
        // or `'x' in slug` without NameError. Lock down the empty-dict
        // contract since the borrow planner can stage an envelope whose
        // producer emitted nothing of value.
        let (stdout, stderr, code) = run_runner(
            r#"print(len(review), review.get("missing", "default"), "x" in review)"#,
            &[("review.json", "{}")],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "0 default False");
    }

    #[tokio::test]
    async fn nested_directory_in_inputs_is_ignored() {
        skip_if_env_unsupported!();
        // `_load_inputs` only iterates files (`os.path.isfile`). If the
        // executor stages a subdirectory under inputs/ (e.g. a structured
        // artifact bundle), it must NOT cause a crash and must NOT be
        // promoted as a global.
        let temp = TempDir::new().unwrap();
        let run_dir = temp.path();
        let inputs_dir = run_dir.join("inputs");
        std::fs::create_dir_all(inputs_dir.join("artifacts")).unwrap();
        std::fs::write(
            inputs_dir.join("artifacts").join("nested.json"),
            r#"{"x": 1}"#,
        )
        .unwrap();
        std::fs::write(inputs_dir.join("input.json"), "{}").unwrap();

        let user_path = inputs_dir.join("main.py");
        std::fs::write(&user_path, "print('artifacts' in globals())").unwrap();
        let runner_path = run_dir.join("__runner__.py");
        write_runner(&runner_path, &user_path, &[]).await.unwrap();

        let outputs_dir = run_dir.join("outputs");
        std::fs::create_dir_all(&outputs_dir).unwrap();

        let output = Command::new("python3")
            .arg(&runner_path)
            .env("AITHERICON_RUN_DIR", run_dir)
            .env("AITHERICON_INPUTS_DIR", &inputs_dir)
            .env("AITHERICON_OUTPUTS_DIR", &outputs_dir)
            .env("PYTHONDONTWRITEBYTECODE", "1")
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "stderr: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(String::from_utf8_lossy(&output.stdout).trim(), "False");
    }

    #[tokio::test]
    async fn inputs_dir_env_unset_runs_with_empty_token() {
        skip_if_env_unsupported!();
        // The executor always sets AITHERICON_INPUTS_DIR in production,
        // but the runner must not require it: if unset, _load_inputs
        // returns `{}` and the runner falls through to an empty token —
        // proving the contract that the runner template alone can boot
        // in an isolated env (smoke testing, perf benchmarking).
        let temp = TempDir::new().unwrap();
        let run_dir = temp.path();
        let user_path = run_dir.join("main.py");
        std::fs::write(
            &user_path,
            "print(len(inputs), len(token), 'review' in globals())",
        )
        .unwrap();
        let runner_path = run_dir.join("__runner__.py");
        write_runner(&runner_path, &user_path, &[]).await.unwrap();

        let output = Command::new("python3")
            .arg(&runner_path)
            .env("AITHERICON_RUN_DIR", run_dir)
            .env_remove("AITHERICON_INPUTS_DIR")
            .env_remove("AITHERICON_OUTPUTS_DIR")
            .env("PYTHONDONTWRITEBYTECODE", "1")
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "stderr: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(
            String::from_utf8_lossy(&output.stdout).trim(),
            "0 0 False"
        );
    }

    #[tokio::test]
    async fn slug_name_matching_input_stem_does_not_collide() {
        skip_if_env_unsupported!();
        // Edge: `input.json` is the slim token; the slug-promotion loop
        // explicitly excludes it. So a producer slug NAMED "input" would
        // collide; the borrow planner reserves the name. Make sure that
        // even if such a file slipped through (or `input.json` were the
        // ONLY file), `input` keeps pointing at the token, not at itself
        // promoted as a global.
        let (stdout, stderr, code) = run_runner(
            "print(input.invoice_id, callable(input.get))",
            &[("input.json", r#"{"invoice_id": "INV-7"}"#)],
        )
        .await;
        assert_eq!(code, 0, "stderr: {stderr}");
        assert_eq!(stdout.trim(), "INV-7 True");
    }

    #[tokio::test]
    async fn set_output_writes_outputs_file() {
        skip_if_env_unsupported!();
        // Verify the file-based set_output fallback still works. The
        // SDK-upgraded path uses IPC; this is the safety net for the
        // no-SDK case (also what these tests exercise).
        let temp = TempDir::new().unwrap();
        let run_dir = temp.path();
        let inputs_dir = run_dir.join("inputs");
        let outputs_dir = run_dir.join("outputs");
        std::fs::create_dir_all(&inputs_dir).unwrap();
        std::fs::create_dir_all(&outputs_dir).unwrap();

        let user_path = inputs_dir.join("main.py");
        std::fs::write(&user_path, r#"set_output("result", {"ok": True, "n": 7})"#)
            .unwrap();
        let runner_path = run_dir.join("__runner__.py");
        write_runner(&runner_path, &user_path, &[]).await.unwrap();

        let output = Command::new("python3")
            .arg(&runner_path)
            .env("AITHERICON_RUN_DIR", run_dir)
            .env("AITHERICON_INPUTS_DIR", &inputs_dir)
            .env("AITHERICON_OUTPUTS_DIR", &outputs_dir)
            .env("PYTHONDONTWRITEBYTECODE", "1")
            .output()
            .unwrap();

        assert!(
            output.status.success(),
            "stderr: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let written =
            std::fs::read_to_string(outputs_dir.join("result.json")).expect("result.json");
        let parsed: serde_json::Value = serde_json::from_str(&written).unwrap();
        assert_eq!(parsed["ok"], serde_json::json!(true));
        assert_eq!(parsed["n"], serde_json::json!(7));
    }

    /// Run the runner with a baked declared-outputs list so the post-exec
    /// sweep is active. Each entry is `(name, required, kind)` — names
    /// come from `output.fields[].name`, kind is the FieldKind string
    /// ("text", "number", "bool", "json", ...) or `None` to skip strict
    /// validation for that name. Returns the TempDir so callers keep it
    /// alive while reading swept outputs.
    async fn run_runner_with_outputs(
        user_script: &str,
        inputs: &[(&str, &str)],
        declared_outputs: &[(String, bool, Option<String>)],
    ) -> (String, String, i32, TempDir) {
        run_runner_with_outputs_env(user_script, inputs, declared_outputs, &[]).await
    }

    /// Like [`run_runner_with_outputs`] but also takes extra env vars to set
    /// when invoking the runner. Lets tests toggle `PETRI_VALIDATE_SCHEMAS`
    /// without duplicating the boilerplate.
    async fn run_runner_with_outputs_env(
        user_script: &str,
        inputs: &[(&str, &str)],
        declared_outputs: &[(String, bool, Option<String>)],
        extra_env: &[(&str, &str)],
    ) -> (String, String, i32, TempDir) {
        let temp = TempDir::new().expect("temp dir");
        let run_dir = temp.path().to_path_buf();
        let inputs_dir = run_dir.join("inputs");
        std::fs::create_dir_all(&inputs_dir).unwrap();

        let user_path = inputs_dir.join("main.py");
        std::fs::write(&user_path, user_script).unwrap();

        for (name, content) in inputs {
            std::fs::write(inputs_dir.join(name), content).unwrap();
        }

        let runner_path = run_dir.join("__runner__.py");
        write_runner(&runner_path, &user_path, declared_outputs)
            .await
            .expect("write_runner");

        let outputs_dir = run_dir.join("outputs");
        std::fs::create_dir_all(&outputs_dir).unwrap();

        let mut cmd = Command::new("python3");
        cmd.arg(&runner_path)
            .env("AITHERICON_RUN_DIR", &run_dir)
            .env("AITHERICON_INPUTS_DIR", &inputs_dir)
            .env("AITHERICON_OUTPUTS_DIR", &outputs_dir)
            .env("PYTHONDONTWRITEBYTECODE", "1");
        for (k, v) in extra_env {
            cmd.env(k, v);
        }
        let output = cmd.output().expect("python3 invocation");

        let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        let code = output.status.code().unwrap_or(-1);
        (stdout, stderr, code, temp)
    }

    #[tokio::test]
    async fn implicit_output_swept_from_global() {
        skip_if_env_unsupported!();
        // The symmetric case to direct-slug-access inputs: declared output
        // `vendor` is assigned as a plain Python global, no `set_output`
        // call. The post-exec sweep promotes it to `vendor.json` so the
        // executor-worker's per-field read picks it up the same way it
        // does for explicit `set_output` writes.
        let (stdout, stderr, code, temp) = run_runner_with_outputs(
            r#"vendor = "ACME""#,
            &[("input.json", "{}")],
            &[("vendor".to_string(), true, None)],
        )
        .await;
        assert_eq!(code, 0, "stdout: {stdout}\nstderr: {stderr}");
        let written = std::fs::read_to_string(temp.path().join("outputs").join("vendor.json"))
            .expect("vendor.json written by sweep");
        assert_eq!(written, "\"ACME\"");
    }

    #[tokio::test]
    async fn explicit_set_output_beats_implicit_sweep() {
        skip_if_env_unsupported!();
        // Explicit-beats-implicit by recency: `set_output` writes the file
        // during `exec`, so when the sweep runs the file already exists and
        // the implicit assignment is skipped. Locks down the "the call you
        // made wins" rule — user can confidently mix both forms.
        let (stdout, stderr, code, temp) = run_runner_with_outputs(
            r#"set_output("vendor", "First"); vendor = "Second""#,
            &[("input.json", "{}")],
            &[("vendor".to_string(), true, None)],
        )
        .await;
        assert_eq!(code, 0, "stdout: {stdout}\nstderr: {stderr}");
        let written = std::fs::read_to_string(temp.path().join("outputs").join("vendor.json"))
            .expect("vendor.json from explicit set_output");
        assert_eq!(written, "\"First\"");
    }

    #[tokio::test]
    async fn required_output_missing_fails_runner() {
        skip_if_env_unsupported!();
        // Required-but-missing is a hard runtime error — declared output
        // `vendor` is required but the user code neither assigns it nor
        // calls `set_output`. The runner must exit non-zero so the
        // executor-worker surfaces the failure cleanly instead of the
        // downstream silently observing a missing output.
        let (stdout, stderr, code, _temp) = run_runner_with_outputs(
            "x = 1",
            &[("input.json", "{}")],
            &[("vendor".to_string(), true, None)],
        )
        .await;
        assert_eq!(code, 2, "stdout: {stdout}\nstderr: {stderr}");
        assert!(
            stderr.contains("missing required output") && stderr.contains("vendor"),
            "stderr: {stderr}"
        );
    }

    /// Hard rejection on kind mismatch (implicit write). Declared output
    /// `vendor` is kind=text but user assigns an integer. The post-exec
    /// validation pass surfaces a precise message at the runner instead of
    /// leaking a generic JSON Schema error far downstream. Exit code 3
    /// distinguishes "schema validation failure" from missing-required (2).
    #[tokio::test]
    async fn kind_mismatch_implicit_rejected() {
        skip_if_env_unsupported!();
        let (stdout, stderr, code, _temp) = run_runner_with_outputs(
            "vendor = 42",
            &[("input.json", "{}")],
            &[("vendor".to_string(), true, Some("text".to_string()))],
        )
        .await;
        assert_eq!(code, 3, "stdout: {stdout}\nstderr: {stderr}");
        assert!(
            stderr.contains("vendor") && stderr.contains("kind='text'") && stderr.contains("int"),
            "stderr: {stderr}"
        );
    }

    /// Kind validation MUST apply to explicit `set_output` too — otherwise
    /// the rule "use the declared port" would have a hole where you can
    /// emit anything via set_output and bypass the contract. Same
    /// validation pass, same exit code, same precision.
    #[tokio::test]
    async fn kind_mismatch_explicit_set_output_rejected() {
        skip_if_env_unsupported!();
        let (stdout, stderr, code, _temp) = run_runner_with_outputs(
            r#"set_output("vendor", 42)"#,
            &[("input.json", "{}")],
            &[("vendor".to_string(), true, Some("text".to_string()))],
        )
        .await;
        assert_eq!(code, 3, "stdout: {stdout}\nstderr: {stderr}");
        assert!(
            stderr.contains("vendor") && stderr.contains("kind='text'"),
            "stderr: {stderr}"
        );
    }

    /// `PETRI_VALIDATE_SCHEMAS=false` opts out of the strict validation
    /// path — same posture as the engine-side flag at
    /// engine/core-engine/src/config.rs:243. The mismatched value still
    /// gets written; the runner just doesn't reject. Useful for emergency
    /// rollback if a kind tightening turns out to be wrong in production.
    #[tokio::test]
    async fn kind_mismatch_disabled_via_env() {
        skip_if_env_unsupported!();
        let (stdout, stderr, code, temp) = run_runner_with_outputs_env(
            "vendor = 42",
            &[("input.json", "{}")],
            &[("vendor".to_string(), true, Some("text".to_string()))],
            &[("PETRI_VALIDATE_SCHEMAS", "false")],
        )
        .await;
        assert_eq!(code, 0, "stdout: {stdout}\nstderr: {stderr}");
        let written = std::fs::read_to_string(temp.path().join("outputs").join("vendor.json"))
            .expect("vendor.json written through despite kind mismatch");
        assert_eq!(written, "42");
    }

    /// `Json` kind is the escape hatch — accepts any JSON value. Locks
    /// down the FieldKind::accepts mirror so a port declared as Json
    /// passes everything: dicts, lists, primitives, mixed nesting.
    #[tokio::test]
    async fn kind_json_accepts_anything() {
        skip_if_env_unsupported!();
        let (stdout, stderr, code, temp) = run_runner_with_outputs(
            r#"blob = {"k": [1, 2, 3], "nested": {"x": True}}"#,
            &[("input.json", "{}")],
            &[("blob".to_string(), true, Some("json".to_string()))],
        )
        .await;
        assert_eq!(code, 0, "stdout: {stdout}\nstderr: {stderr}");
        let written = std::fs::read_to_string(temp.path().join("outputs").join("blob.json"))
            .expect("blob.json written");
        assert!(written.contains("\"nested\""));
    }

    /// Python `True`/`False` are int subclasses — `isinstance(True, int)`
    /// is True, so a naive Number check would silently accept a bool
    /// where a number is required. The runner's `_kind_accepts` checks
    /// `not isinstance(value, bool)` for Number specifically. This test
    /// locks that down: declared kind=number, user writes True → reject.
    #[tokio::test]
    async fn kind_number_rejects_bool() {
        skip_if_env_unsupported!();
        let (stdout, stderr, code, _temp) = run_runner_with_outputs(
            "count = True",
            &[("input.json", "{}")],
            &[("count".to_string(), true, Some("number".to_string()))],
        )
        .await;
        assert_eq!(code, 3, "stdout: {stdout}\nstderr: {stderr}");
        assert!(
            stderr.contains("count") && stderr.contains("kind='number'") && stderr.contains("bool"),
            "stderr: {stderr}"
        );
    }
}
