# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aithericon._proto import executor_sidecar_pb2 as executor__sidecar__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in executor_sidecar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorSidecarStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogArtifact = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/LogArtifact',
                request_serializer=executor__sidecar__pb2.LogArtifactRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.UpdateProgress = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/UpdateProgress',
                request_serializer=executor__sidecar__pb2.UpdateProgressRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.DefinePhases = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/DefinePhases',
                request_serializer=executor__sidecar__pb2.DefinePhasesRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.UpdatePhase = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/UpdatePhase',
                request_serializer=executor__sidecar__pb2.UpdatePhaseRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.LogMessage = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/LogMessage',
                request_serializer=executor__sidecar__pb2.LogMessageRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.SetOutput = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/SetOutput',
                request_serializer=executor__sidecar__pb2.SetOutputRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.LogMetrics = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/LogMetrics',
                request_serializer=executor__sidecar__pb2.LogMetricsRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/HealthCheck',
                request_serializer=executor__sidecar__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.ShutdownAck = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/ShutdownAck',
                request_serializer=executor__sidecar__pb2.ShutdownAckRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.EmitControl = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/EmitControl',
                request_serializer=executor__sidecar__pb2.EmitControlRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.StreamChunks = channel.unary_stream(
                '/aithericon.executor.ipc.ExecutorSidecar/StreamChunks',
                request_serializer=executor__sidecar__pb2.StreamChunksRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.ChunkMessage.FromString,
                _registered_method=True)
        self.PublishChunk = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/PublishChunk',
                request_serializer=executor__sidecar__pb2.PublishChunkRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.SidecarResponse.FromString,
                _registered_method=True)
        self.RetrieveFile = channel.unary_unary(
                '/aithericon.executor.ipc.ExecutorSidecar/RetrieveFile',
                request_serializer=executor__sidecar__pb2.RetrieveFileRequest.SerializeToString,
                response_deserializer=executor__sidecar__pb2.RetrieveFileResponse.FromString,
                _registered_method=True)


class ExecutorSidecarServicer:
    """Missing associated documentation comment in .proto file."""

    def LogArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DefinePhases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePhase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutdownAck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitControl(self, request, context):
        """Dynamic control-token emission into a statically-declared output channel.
        CONTROL plane: the child emits a `signal` (one control token) or a
        `scatter` (N instance-colored items bracketed by a close that stamps the
        count). DATA plane (1b): the child emits an `open` (carrying the JSON
        transport DESCRIPTOR of a data channel it just opened) so the consumer can
        start draining the out-of-band byte stream EARLY, then a `close` (stamping
        the element count + terminal status) once the producer is done writing.
        The sidecar validates the name+plane against the manifest, then publishes a
        `control_emit` event to the EXECUTOR_EVENTS JetStream stream
        (subject `executor.events.{execution_id}.control_emit`) which the engine
        ingests to deposit a token into the channel's place. Fire-and-forget: the
        engine never gates the emit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChunks(self, request, context):
        """Data-plane CONSUMER read (`for elem in aithericon.stream(name)`): the
        child opens this server-stream passing the PRODUCER's transport subject
        (lifted from the `open` descriptor the engine delivered as this job's
        input). The executor subscribes to that subject over the data-plane
        `StreamTransport` and relays each binary envelope here while the producer
        is still writing. Each yielded `ChunkMessage` is a binary envelope
        `{ seq, content_type, payload, is_eof }`; the stream ends after the
        in-band EOF sentinel (`ChunkMessage{is_eof:true}`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishChunk(self, request, context):
        """Outbound byte stream: the producer writer (`open_output(name)`) hands the
        executor one framed element at a time; the executor publishes the binary
        envelope onto the channel's datastream transport subject
        (`executor.datastream.{execution_id}.{channel}`) so a consumer elsewhere
        can drain it. The SDK holds no NATS/transport credentials; the executor
        does. Unary + ordered: the writer awaits each publish so the transport's
        ack window can back-pressure a too-fast producer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveFile(self, request, context):
        """Inbound file retrieval: the child asks the sidecar (which holds storage
        credentials — the child does not) to download a storage-path object into
        the run directory and return its local path. Backs the Python SDK's
        `aithericon.File.retrieve()` — e.g. lazily fetching an asset record's
        `File`-field value (a storage path) only for the row the code selected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorSidecarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.LogArtifact,
                    request_deserializer=executor__sidecar__pb2.LogArtifactRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'UpdateProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProgress,
                    request_deserializer=executor__sidecar__pb2.UpdateProgressRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'DefinePhases': grpc.unary_unary_rpc_method_handler(
                    servicer.DefinePhases,
                    request_deserializer=executor__sidecar__pb2.DefinePhasesRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'UpdatePhase': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePhase,
                    request_deserializer=executor__sidecar__pb2.UpdatePhaseRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'LogMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.LogMessage,
                    request_deserializer=executor__sidecar__pb2.LogMessageRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'SetOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOutput,
                    request_deserializer=executor__sidecar__pb2.SetOutputRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'LogMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.LogMetrics,
                    request_deserializer=executor__sidecar__pb2.LogMetricsRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=executor__sidecar__pb2.HealthCheckRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'ShutdownAck': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutdownAck,
                    request_deserializer=executor__sidecar__pb2.ShutdownAckRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'EmitControl': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitControl,
                    request_deserializer=executor__sidecar__pb2.EmitControlRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'StreamChunks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChunks,
                    request_deserializer=executor__sidecar__pb2.StreamChunksRequest.FromString,
                    response_serializer=executor__sidecar__pb2.ChunkMessage.SerializeToString,
            ),
            'PublishChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishChunk,
                    request_deserializer=executor__sidecar__pb2.PublishChunkRequest.FromString,
                    response_serializer=executor__sidecar__pb2.SidecarResponse.SerializeToString,
            ),
            'RetrieveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveFile,
                    request_deserializer=executor__sidecar__pb2.RetrieveFileRequest.FromString,
                    response_serializer=executor__sidecar__pb2.RetrieveFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aithericon.executor.ipc.ExecutorSidecar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aithericon.executor.ipc.ExecutorSidecar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutorSidecar:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/LogArtifact',
            executor__sidecar__pb2.LogArtifactRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/UpdateProgress',
            executor__sidecar__pb2.UpdateProgressRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DefinePhases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/DefinePhases',
            executor__sidecar__pb2.DefinePhasesRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePhase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/UpdatePhase',
            executor__sidecar__pb2.UpdatePhaseRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/LogMessage',
            executor__sidecar__pb2.LogMessageRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/SetOutput',
            executor__sidecar__pb2.SetOutputRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/LogMetrics',
            executor__sidecar__pb2.LogMetricsRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/HealthCheck',
            executor__sidecar__pb2.HealthCheckRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShutdownAck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/ShutdownAck',
            executor__sidecar__pb2.ShutdownAckRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/EmitControl',
            executor__sidecar__pb2.EmitControlRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/StreamChunks',
            executor__sidecar__pb2.StreamChunksRequest.SerializeToString,
            executor__sidecar__pb2.ChunkMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/PublishChunk',
            executor__sidecar__pb2.PublishChunkRequest.SerializeToString,
            executor__sidecar__pb2.SidecarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aithericon.executor.ipc.ExecutorSidecar/RetrieveFile',
            executor__sidecar__pb2.RetrieveFileRequest.SerializeToString,
            executor__sidecar__pb2.RetrieveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
